# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ICYMORN | 寒霜之晨
email: im.moevis@gmail.com
description: 诗与编程
baseurl: "" 
url: "https://moevis.github.io" # the base hostname & protocol for your site
twitter_username: moevery
github_username: moevis
paginate: 5
theme-dark: false #Set to true to change to dark website theme

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
